In [1]:
# Create a list

my_list = [10, 20, 30, 'apple', 'true', 8, 10]
print(my_list)

[10, 20, 30, 'apple', 'true', 8, 10]


In [2]:
# Reverse the list

reversed_list = my_list[::-1]
print(reversed_list)

[10, 8, 'true', 'apple', 30, 20, 10]


In [2]:
# Append new elements to the list

my_list.append(30)
my_list.append(40)

In [4]:
print(my_list)

[10, 20, 30, 'apple', 'true', 8, 10, 30, 40]


In [5]:
# Create a dictionary

a = {1: 'data', 2: 'information', 3: 'test'}
print(a)

{1: 'data', 2: 'information', 3: 'test'}


In [6]:
# Delete an item

del a[3]
print(a)

{1: 'data', 2: 'information'}


In [22]:
# Add a new item

a[3] = 'features'
print(a)

{1: 'data', 2: 'information', 3: 'features'}


In [ ]:
print(a[1])
print(a)

data
{1: 'data', 2: 'information', 3: 'features'}


In [8]:
# Create tuples


tuple1 = (1, 2, 3, 'apple', 'mango')
tuple2 = (10, 20, 30, 40, 50)
print(tuple1)
print(tuple2)

(1, 2, 3, 'apple', 'mango')
(10, 20, 30, 40, 50)


In [9]:
#minimum value in a tuple

small_value = min(tuple2)
print(small_value)

10


In [10]:
# Concatenate tuples

concatenate = tuple1 + tuple2
print(concatenate)

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)


In [11]:
# Duplicate the concatenated tuple

duplicate = concatenate * 2
print(duplicate)

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50, 1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)


In [12]:
# Create sets
set1 = {1, 2, 3, 4, 5}
set2 = {1, 2, 3, 6, 7}

In [13]:
print(set1)
print(set2)

{1, 2, 3, 4, 5}
{1, 2, 3, 6, 7}


In [14]:
union = set1.union(set2)
print(union)

{1, 2, 3, 4, 5, 6, 7}


In [15]:
intersection = set1.intersection(set2)
print(intersection)

{1, 2, 3}


In [20]:
difference = set1.difference(set2)
print(difference)
print(set1,set2,union,intersection,difference)

{4, 5}
{1, 2, 3, 4, 5} {1, 2, 3, 6, 7} {1, 2, 3, 4, 5, 6, 7} {1, 2, 3} {4, 5}


In [45]:
import numpy as np

# Task 1: Create a 3x3 matrix array with values ranging from 2 to 10
matrix = np.linspace(2, 10, 9).reshape(3, 3)
print( matrix)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [46]:
# Task 2: User input array converted to float type
input_array = np.array([1, 2, 3, 4])
float_array = input_array.astype(float)
print(float_array)

[1. 2. 3. 4.]


In [47]:
# Task 3: Append values to the end of an array
original_array = np.array([10, 20, 30])
appended_array = np.append(original_array, [40, 50, 60, 70, 80, 90])
print(appended_array)

[10 20 30 40 50 60 70 80 90]


In [49]:
# Task 4: Sum of two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_array = array1 + array2
print(sum_array)

[5 7 9]


In [50]:
# Task 5: Create a 3x3 array from 10 to 90 with an interval of 10
array1 = np.arange(10, 100, 10).reshape(3, 3)
print(array1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [51]:
# a. Extract the 1st row
first_row = array1[0, :]
print(first_row)

[10 20 30]


In [52]:
# b. Extract the last element
last_element = array1[-1, -1]
print( last_element)

90
